name: Node.js Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install backend dependencies
      run: cd backend && npm install

    - name: Install frontend dependencies
      run: cd frontend && npm install --force

    - name: Build React frontend
      run: cd frontend && CI=false npm run build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: Matrix-React-App
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC5DF6EC1BE54B6DBCE7A2178E53D175 }}
        package: .
